### ISSUE TITLE
HTTP error 500 after checking out using Laybuy

### ISSUE THREAD

**Issue by rocwang** [Laybuy/Magento-1#1]
Hi Carl,

I was investigating an issue for a client, where customers saw the HTTP 500 error page after checking out using Laybuy from Magento.

Here is the stack trace for multiple occurrences:

```
[Tue Sep 12 12:36:42 2017] [error] [client 121.99.181.227]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mage_Payment_Helper_Data::getInfoBlock() must be an instance of Mage_Payment_Model_Info, boolean given, called in app/code/core/Mage/Sales/Model/Order.php on line 1269 and defined in app/code/core/Mage/Payment/Helper/Data.php:117
Stack trace:
#0 app/code/core/Mage/Sales/Model/Order.php(1269): Mage_Payment_Helper_Data->getInfoBlock(false)
#1 app/code/community/Laybuy/Payments/controllers/PaymentController.php(88): Mage_Sales_Model_Order->sendNewOrderEmail()
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(419): Laybuy_Payments_PaymentController->responseAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('response')
#4 app/code/core/Mage/Core/Controller/Vari in app/code/core/Mage/Payment/Helper/Data.php on line 117, referer: https://payment.laybuy.com/pay/ICOZQUAKYBUE1gCaVxgRzeRPcu6kCmoOVBQlhOZG

[Tue Sep 12 12:36:51 2017] [error] [client 121.99.181.227]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mage_Payment_Helper_Data::getInfoBlock() must be an instance of Mage_Payment_Model_Info, boolean given, called in app/code/core/Mage/Sales/Model/Order.php on line 1269 and defined in app/code/core/Mage/Payment/Helper/Data.php:117
Stack trace:
#0 app/code/core/Mage/Sales/Model/Order.php(1269): Mage_Payment_Helper_Data->getInfoBlock(false)
#1 app/code/community/Laybuy/Payments/controllers/PaymentController.php(88): Mage_Sales_Model_Order->sendNewOrderEmail()
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(419): Laybuy_Payments_PaymentController->responseAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('response')
#4 app/code/core/Mage/Core/Controller/Vari in app/code/core/Mage/Payment/Helper/Data.php on line 117

[Tue Sep 12 12:37:51 2017] [error] [client 121.99.32.138]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mage_Payment_Helper_Data::getInfoBlock() must be an instance of Mage_Payment_Model_Info, boolean given, called in app/code/core/Mage/Sales/Model/Order.php on line 1269 and defined in app/code/core/Mage/Payment/Helper/Data.php:117
Stack trace:
#0 app/code/core/Mage/Sales/Model/Order.php(1269): Mage_Payment_Helper_Data->getInfoBlock(false)
#1 app/code/community/Laybuy/Payments/controllers/PaymentController.php(88): Mage_Sales_Model_Order->sendNewOrderEmail()
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(419): Laybuy_Payments_PaymentController->responseAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('response')
#4 app/code/core/Mage/Core/Controller/Vari in app/code/core/Mage/Payment/Helper/Data.php on line 117, referer: https://payment.laybuy.com/pay/UnVaEAy1exJZh15XlYmNXfSGi8ZIB4XL3fV1SfuI

[Tue Sep 12 12:38:02 2017] [error] [client 121.99.32.138]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mage_Payment_Helper_Data::getInfoBlock() must be an instance of Mage_Payment_Model_Info, boolean given, called in app/code/core/Mage/Sales/Model/Order.php on line 1269 and defined in app/code/core/Mage/Payment/Helper/Data.php:117
Stack trace:
#0 app/code/core/Mage/Sales/Model/Order.php(1269): Mage_Payment_Helper_Data->getInfoBlock(false)
#1 app/code/community/Laybuy/Payments/controllers/PaymentController.php(88): Mage_Sales_Model_Order->sendNewOrderEmail()
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(419): Laybuy_Payments_PaymentController->responseAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('response')
#4 app/code/core/Mage/Core/Controller/Vari in app/code/core/Mage/Payment/Helper/Data.php on line 117, referer: https://payment.laybuy.com/pay/UnVaEAy1exJZh15XlYmNXfSGi8ZIB4XL3fV1SfuI

[Tue Sep 12 12:38:20 2017] [error] [client 121.99.32.138]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mage_Payment_Helper_Data::getInfoBlock() must be an instance of Mage_Payment_Model_Info, boolean given, called in app/code/core/Mage/Sales/Model/Order.php on line 1269 and defined in app/code/core/Mage/Payment/Helper/Data.php:117
Stack trace:
#0 app/code/core/Mage/Sales/Model/Order.php(1269): Mage_Payment_Helper_Data->getInfoBlock(false)
#1 app/code/community/Laybuy/Payments/controllers/PaymentController.php(88): Mage_Sales_Model_Order->sendNewOrderEmail()
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(419): Laybuy_Payments_PaymentController->responseAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('response')
#4 app/code/core/Mage/Core/Controller/Vari in app/code/core/Mage/Payment/Helper/Data.php on line 117, referer: https://payment.laybuy.com/pay/UnVaEAy1exJZh15XlYmNXfSGi8ZIB4XL3fV1SfuI

```
I tried to replicate the issue on the staging site, but the checking out process succeeded without this issue on staging.

After some code digging, I came up with the following theory:

See 
https://github.com/Laybuy/Magento1/blob/bb83ec054d13866187092042505efeacf37f8c13/app/code/community/Laybuy/Payments/controllers/PaymentController.php#L85

The order object is supposed to be populated with data by the loadByIncrementId() method. However, it might fail silently and leave an empty order object if the provided increment id is not valid somehow. 

https://github.com/Laybuy/Magento1/blob/bb83ec054d13866187092042505efeacf37f8c13/app/code/community/Laybuy/Payments/controllers/PaymentController.php#L88

In the following call to Mage_Sales_Model_Order->sendNewOrderEmail(), Mage_Sales_Model_Order->getPayment() was called but can only return false due the failure of order loading. The false value is then passed to Mage::helper('payment')->getInfoBlock() in Mage_Sales_Model_Order->sendNewOrderEmail(), which trigger the fatal error above in the stack trace.

I found that the reserved the order increment id in the quote is different from the actual order increment id. Maybe that's worth investigation?

**Comment by carlbowden** [comment]
Hi Roc,

Alex got in touch and noted:

> I did a bit of further investigation. I believe it was caused by the RetailExpress extension installed on braonzesanke.com
> It overwrites the order ID using the order ID in RetailExpress, which caused the issue. That’s also why I can’t replicate the issue on the staging site, which doesn’t have RetailExpress enabled.

was this you? It would make sense, what other Payment modules are installed on BS site (like DPS or something)?

ta Carl.

**Comment by rocwang** [comment]
Yes, that's me. They have eWay and other payment module installed and enabled on site. I still think the order increment ID overwriting from RetailExpress is probably the culprit. Maybe the quote ID can be used to load the order rather than the reserved increment ID as a fallback in the extension?

**Comment by carlbowden** [comment]
Hi, Roc, I have pushed a change up, looking through the other module, they extend the payment object with their own properties, which seemed unnecessary initially, but I now see why. I think it's almost certainly an approach we will need to take in a future update. At in staying that other module also pull the order ID from the current session, which I have done with this push, and then try to load the order again

**Comment by rocwang** [comment]
Thanks, Carl! The update should fix the issue.
I'm closing the issue now.

**Comment by carlbowden** [comment]
Hi Roc, 

it seems like we have got and report that this hasn't worked, 

I can't download the current eWay Magento 1 module (Magento have just changed the module site) could you send me a zip of the one on BS

 is it possible these modules that are working on BS have been customised for this? 

The only other way is that we keep our own session values and get them to pull up the order, what doesn't make sense is that if the order we are using the expected orderID and when e get back ist gone, what would I store? 

it's pretty tricky without a working dev environment
