### ISSUE TITLE
The $totalOrderValue is incorrectly hardcoded in Payments.php

### ISSUE THREAD

**Issue by rocwang** [Laybuy/Magento-1#2]
https://github.com/Laybuy/Magento1/blob/a0c241b5c38fb010bf0a81019d208eac085b080b/app/code/community/Laybuy/Payments/Model/Payments.php#L220

The $totalOrderValue is incorrectly hardcoded to be 10 there, which looks like a debugging statement supposed to be deleted.

**Comment by carlbowden** [comment]
Hi Roc, this was resolved with the 109f4a5  push
