### ISSUE TITLE
Order/Invoice view missing the payment/transactions details

### ISSUE THREAD

**Issue by IbrahimS2** [Laybuy/Magento-1#8]
No payment information registered or viewable from the order view page:

![image](https://user-images.githubusercontent.com/19901858/55023915-78e7e500-5006-11e9-9438-5244c16560b1.png)

**Comment by jonaschen623** [comment]
My fix:

add one file:
app/design/adminhtml/default/default/template/laybuy/payments/info.phtml

`<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
`

**Comment by IbrahimS2** [comment]
@alex-overdose @jonaschen623 Yes I do see that the extension itself calling info.phtml and method.phtml; the annoying part is the whole repository does not include these template files! not sure how they messed it.

They should include the Auth Code right there instead of adding it as a comment if you want my opinion.

**Comment by IbrahimS2** [comment]
@alex-overdose This has been resolved with the coming release, therefore I am going to close it.
